[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "01daed5b1099ad37c049eb7bbc22fd3923295dff"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "078d187a6429f5471ccc6cbfb85603b628e0e5e1a96361875854f4d14660db5c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.aarch64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "b86904f226b6f516a31d1526fd8c12e4a32a8ffa"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "25030f50363dde4007be2a84dff7c3fbbccbe1717f4d281fd60d0c380b32c37b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.aarch64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "8242138f99aa27cf841b722520b1931fb5bb8e34"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "5e537fa995c87279e7118d622956f142798a207e1db43678e16dcd63547bc3f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.aarch64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "aarch64"
git-tree-sha1 = "b13110d4656951e46be9b278c58ca9646b9eea82"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "01a68b0099056e8717b365d191b5e194b307510e2f3e90b975b751dd11c01cba"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf370664137bc23f22ddc89fc38bde94a2d5d4e1"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "eca7fd12d316dddd95c1c6e29e150ec884a2741745aab4251cf57cfb2496a8a4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "110532cc1599221fb80082c978aa19b27160b14d"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "22a3e08b4503c5f7376bcac4bcf13f3b11772ea59f2bc9fc040873809afc200e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dac91012dd8cfa0b75ac18400b386384eab52565"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "05eb5a889bc35e05c7192c6041fd86df9222ad5d68069247cebadb7f0cf1d454"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_s3]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c458b6a7c50399ef43d800f1fd775c26fb993f14"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "da338b393710cf4bebce5d93d365e0c58478536c0d6be6bed8a61c6ec3a3c4f6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "55151a987ebd70928750497d659f324987ed9bcc"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "03f8cedd9d527f7adb30fe6e30956b86558aad2328a35bef6a19d271a29d9943"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.i686-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "i686"
git-tree-sha1 = "27b886e8b9a0877b3de38adcf5631e1539104185"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "9745c3c05c54f3624c70c9282e465f8b75891c1c318152dc180a5bc21684e9d7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.i686-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "powerpc64le"
git-tree-sha1 = "f1231b612e32d88c98285eb7dc40ba152706992c"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "aadc35f62ccfceecf733bd53c4d1efde91bee8043fd1ddecc756bb7f94f68d20"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "riscv64"
git-tree-sha1 = "dbbf4cf5fb9b4f2244488c0f4e2f7d1ad4953ca1"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "7c8ea4440d19ac74b3192f2148eca872c89f3b911a8b218ebebcdbc2a71d7447"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.riscv64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "22948de3fe50de184f2cc94f0c5ce3a5343be5fe"
os = "macos"

    [[aws_c_s3.download]]
    sha256 = "fc4092cecf773987fde0378a0668199069cb9b10f635c30be9263ff5bbbb4199"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.x86_64-apple-darwin.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "864f56f491fe1b3d1e38b6abd3842589861d0054"
libc = "glibc"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "654e74e0ca7798d1bd9dda3d914e9bf66562f410b0c23ca1091f89245c7a61dd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.x86_64-linux-gnu.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "a5bafef983eeb6a3f3b9945d13dcc2eda5b508f1"
libc = "musl"
os = "linux"

    [[aws_c_s3.download]]
    sha256 = "278a37a957eb1c49ea9b0ba7f2a1791226243c57acd265abf8261885cb8de5b1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.x86_64-linux-musl.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "2453f4411bf1bc1dfd5b0f15159209fdad532e68"
os = "freebsd"

    [[aws_c_s3.download]]
    sha256 = "ef6f462fe702f130955816b88d544de929fffd0b9d7f0af837530c61ef5b9aac"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_s3]]
arch = "x86_64"
git-tree-sha1 = "6c8808aa4364ef341d618b7ea5656e6d2ad29e5a"
os = "windows"

    [[aws_c_s3.download]]
    sha256 = "d9c364ebe8859c5e37dd0735d3b1cb45e86e7d1c267158a5703d5baf4c83912c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_s3_jll.jl/releases/download/aws_c_s3-v1.3.0+0/aws_c_s3.v1.3.0.x86_64-w64-mingw32.tar.gz"
